### ISSUE TITLE
[Bug]An error occurred in the calculation of 5.6/28.

### ISSUE THREAD

**Issue by ZiuChen** [francislee-cn/utools-simple-calculator#1]
As you can see, when calculating 5.6/28, there is a situation that can not be divided. I want to know whether this is my reason or the plug-in's reason. Thank you!
如你所见，在计算5.6/28时出现除不尽的情况，我想知道这是我的原因还是插件的原因，谢谢！

![Snipaste_2021-11-09_20-34-01](https://user-images.githubusercontent.com/64892985/140928847-3cc8a0b4-c781-49a1-9653-99e9a38c5ac1.jpg)

**Comment by francislee-cn** [comment]
是插件的原因

**Comment by francislee-cn** [comment]
@ZiuChen 插件发布审核需要些时间 请耐心等待
或者 你也可以移步 [Releases](https://github.com/francislee-cn/utools-simple-calculator/releases/tag/1.0.1) 手动安装新版
