### ISSUE TITLE
在计算2^2时出现错误

### ISSUE THREAD

**Issue by ZiuChen** [francislee-cn/utools-simple-calculator#2]
如你所见，插件在计算2^2时出现错误。
As you can see, the plugin has an error when calculating 2^2.
![image](https://user-images.githubusercontent.com/64892985/141220627-2cae58a8-02a1-49e3-97db-5aa9a01c880d.png)

**Comment by francislee-cn** [comment]
目前只支持加减乘除运算 后续可能会支持更复杂的计算

**Comment by francislee-cn** [comment]
1.1.x版本已支持
